package:
  name: assaytools-dev
  version: 0.0.0

source:
  path: ../..

build:
  entry_points:
    - xml2png = assaytools.scripts.xml2png:entry_point

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pandas
    - scipy
    - openblas
    - pymc
    - matplotlib
    - seaborn
    - lxml
    - libxslt=1.1.29-2
    - ipython
    - notebook
    - autoprotocol
    - mock
    - pymbar

  run:
    - python
    - numpy
    - pint
    - pandas
    - scipy
    - openblas
    - pymc
    - matplotlib
    - seaborn
    - lxml
    - libxslt=1.1.29-2
    - ipython
    - notebook
    - autoprotocol
    - pymbar

test:
  imports:
    - assaytools

about:
  home: http://assaytools.choderalab.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A library for the modeling and analysis of plate-based assays (development snapshot)
